{
  size: [320, 512],
  layers: [1, 4, 4, 8, 8, 4],
  channels: [16, 32, 64, 128, 256, 512, 1024],
  slice_point: [1, 3, 5, 6, 30],
  all_anchors: 
    [
      [[0.31242, 0.29083], [0.36752, 0.45009], [0.59300, 0.44627]], 
      [[0.45821, 0.65497], [0.62137, 0.67607], [0.83896, 0.64288]],
      [[0.68232, 0.90531], [1.06267, 0.78875], [0.92839, 1.03793]]
    ], # (3, 3, 2)
  classes:
    [
      [0.00, 0.00],    [15.00, 0.00],   [30.00, 0.00],   [45.00, 0.00],   [60.00, 0.00],   #4
      [75.00, 0.00],   [90.00, 0.00],   [105.00, 0.00],  [120.00, 0.00],  [135.00, 0.00],  #9
      [150.00, 0.00],  [165.00, 0.00],  [180.00, 0.00],  [195.00, 0.00],  [210.00, 0.00],  #14
      [225.00, 0.00],  [240.00, 0.00],  [255.00, 0.00],  [270.00, 0.00],  [285.00, 0.00],  #19
      [300.00, 0.00],  [315.00, 0.00],  [330.00, 0.00],  [345.00, 0.00]                    #24
    ],

  ############ Train ############
  record_step: 10000,
  valid_step: 1000, 
  batch_size: 12,
  train_counter_start: 0,
  
  loss_name: 
    [
      'score', 'box_yx', 'box_hw', 'rotate', 'class',
      'LP_score', 'LP_xy', 'LP_z', 'LP_r', 'LP_class'
    ],
  scale: 
    {
      'score': 0.1, 'box_yx': 0.1, 'box_hw': 10.0, 'rotate': 0.0, 'class': 0.1,
      'LP_score': 0.1, 'LP_xy': 10.0, 'LP_z': 10.0, 'LP_r': 0.1, 'LP_class': 0.0
    },
  learning_rate: 0.001,
  positive_weight: 1.0,
  negative_weight: 0.1,
  dataset: 'c100',

  ############ Licence Plate ############
  LP_slice_point: [1, 3, 4, 7, 10],
  LP_positive_weight: 1.0,
  LP_negative_weight: 0.1,
  LP_r_max: [45, 60, 45],
  LP_num_class: 3,

  ############ Validation ############
  pub_img: '/YOLO/img',
  pub_box: '/YOLO/box',

  pub_clipped_LP: /YOLO/clipped_LP,
  pub_LP: '/YOLO/LP',

  iou_bs: 30,
}
