{
  use_fp16: false,
  size: [320,512],
  num_init_features: 64,
  growth_rate: 24,
  block_config: [6, 12, 24, 16],
  layers: [1, 1, 1, 1, 1],
  # len(layers) = len(block_config) + 1
  # value of layers is necessary
  slice_point: [1, 3, 5, 6, 30],
  all_anchors:
    [[[0.2216, 0.1552],  [0.2825, 0.3456], [0.3703, 0.4351],
      [0.4345, 0.6063],  [0.7448, 0.6772]]], # (1, 5, 2)
  classes:
    [
      [0.00, 0.00],    [15.00, 0.00],   [30.00, 0.00],   [45.00, 0.00],   [60.00, 0.00],   #4
      [75.00, 0.00],   [90.00, 0.00],   [105.00, 0.00],  [120.00, 0.00],  [135.00, 0.00],  #9
      [150.00, 0.00],  [165.00, 0.00],  [180.00, 0.00],  [195.00, 0.00],  [210.00, 0.00],  #14
      [225.00, 0.00],  [240.00, 0.00],  [255.00, 0.00],  [270.00, 0.00],  [285.00, 0.00],  #19
      [300.00, 0.00],  [315.00, 0.00],  [330.00, 0.00],  [345.00, 0.00]],

  ############ Train ############
  record_step: 10000,
  valid_step: 1000,
  batch_size: 24,
  train_counter_start: 0,

  loss_name: ['score', 'box_yx', 'box_hw', 'rotate', 'class'],
  scale: {'score': 0.1, 'box_yx': 0.1, 'box_hw': 10.0, 'rotate': 0.0, 'class': 0.1},
  learning_rate: 0.001,
  positive_weight: 1.0,
  negative_weight: 0.1,
  dataset: 'c200_ele60',

  ############ Validation ############
  pub_img: '/YOLO/img',
  pub_box: '/YOLO/box'
}

